name: Bob the Builder

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: Restore Cache of dl/
        uses: actions/cache@v3
        with:
          path: dl/
          key: dl-${{ hashFiles('.git/modules/buildroot/HEAD', 'configs/*') }}
          restore-keys: |
            dl-
      - name: Restore Cache of .ccache/
        uses: actions/cache@v3
        with:
          path: .ccache/
          key: ccache-${{ hashFiles('.git/modules/buildroot/HEAD', 'configs/*') }}
          restore-keys: |
            ccache-
      - name: Configure & Build
        run: |
          make qemu_x86_64_defconfig
          make
      - name: Prepare Artifact
        run: |
          cd output
          mv images br2-finit-demo
          ln -s br2-finit-demo images
          tar chfz br2-finit-demo.tgz br2-finit-demo
      - uses: actions/upload-artifact@v4
        with:
          path: output/br2-finit-demo.tgz
